name: gradle bundleRelease

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
    
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAB
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: bundleRelease
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: bundle-release
          path: app/build/outputs/bundle/release
