name: Upload Apk
on: workflow_dispatch
jobs:
  build:
    name: Build Debug Apk 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running gradle assembleDebug
      run: gradle assembleDebug

    - name: Uploading Apk and Files
      uses: actions/upload-artifact@v2
      with:
        name: All
        path: |
            app/build/outputs/apk/debug
            app/build/generated
      
    
